# Generated by Django 5.0 on 2026-07-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_visitas/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de upload')),
            ],
            options={
                'verbose_name': 'Foto da Visita',
                'verbose_name_plural': 'Fotos das Visitas',
            },
        ),
        migrations.CreateModel(
            name='PragaDoenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da praga/doença')),
                ('severidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='baixa', max_length=10, verbose_name='Severidade')),
                ('data_deteccao', models.DateField(verbose_name='Data de deteção')),
                ('tratamento_sugerido', models.TextField(blank=True, verbose_name='Tratamento sugerido')),
                ('resolvido', models.BooleanField(default=False, verbose_name='Resolvido')),
            ],
            options={
                'verbose_name': 'Praga/Doença',
                'verbose_name_plural': 'Pragas/Doenças',
                'ordering': ['-data_deteccao'],
            },
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da recomendação')),
                ('dados_solo', models.TextField(blank=True, help_text='pH, nutrientes, matéria orgânica...', verbose_name='Dados do solo')),
                ('dados_clima', models.TextField(blank=True, help_text='Temperatura, precipitação, humidade...', verbose_name='Dados do clima')),
                ('texto_recomendacao', models.TextField(verbose_name='Recomendação técnica')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('emitida', 'Emitida'), ('aplicada', 'Aplicada pelo agricultor')], default='emitida', max_length=10, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Recomendação',
                'verbose_name_plural': 'Recomendações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='VisitaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da visita')),
                ('tipo', models.CharField(choices=[('rotineira', 'Rotineira'), ('urgente', 'Urgente'), ('avaliacao', 'Avaliação'), ('monitoramento', 'Monitoramento')], default='rotineira', max_length=20, verbose_name='Tipo de visita')),
                ('observacoes', models.TextField(verbose_name='Observações técnicas')),
                ('recomendacao_campo', models.TextField(blank=True, verbose_name='Recomendações de campo')),
            ],
            options={
                'verbose_name': 'Visita Técnica',
                'verbose_name_plural': 'Visitas Técnicas',
                'ordering': ['-data'],
            },
        ),
    ]
