# Generated by Django 5.0 on 2026-07-10 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultoria', '0001_initial'),
        ('propriedades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pragadoenca',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pragas_doencas', to='propriedades.talhao', verbose_name='Talhão'),
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='consultor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Consultor'),
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes', to='propriedades.talhao', verbose_name='Talhão'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='propriedades.propriedade', verbose_name='Propriedade'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável (Consultor/Técnico)'),
        ),
        migrations.AddField(
            model_name='fotovisita',
            name='visita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='consultoria.visitatecnica', verbose_name='Visita'),
        ),
    ]
