# Generated by Django 5.0 on 2026-07-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pragadoenca',
            name='foto_diagnostico',
            field=models.ImageField(blank=True, null=True, upload_to='pragas/diagnosticos/', verbose_name='Foto do diagnóstico'),
        ),
        migrations.AddField(
            model_name='pragadoenca',
            name='foto_resultado',
            field=models.ImageField(blank=True, null=True, upload_to='pragas/resultados/', verbose_name='Foto após tratamento'),
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='recomendacoes/evidencias/', verbose_name='Foto de evidência'),
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='foto_resultado',
            field=models.ImageField(blank=True, null=True, upload_to='recomendacoes/resultados/', verbose_name='Foto do resultado'),
        ),
    ]
