# Generated by Django 5.0 on 2026-07-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='justificativa_solicitacao',
            field=models.TextField(blank=True, verbose_name='Justificativa da solicitação'),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='perfil_solicitado',
            field=models.CharField(blank=True, choices=[('visitante', 'Visitante'), ('consultor', 'Consultor Agrícola'), ('analista', 'Analista de Dados'), ('tecnico', 'Técnico de Campo'), ('agricultor', 'Agricultor')], max_length=20, verbose_name='Perfil solicitado'),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='status_solicitacao',
            field=models.CharField(choices=[('sem_pedido', 'Sem pedido'), ('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='sem_pedido', max_length=20, verbose_name='Estado da solicitação'),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='tipo_utilizador',
            field=models.CharField(choices=[('visitante', 'Visitante'), ('admin', 'Administrador'), ('consultor', 'Consultor Agrícola'), ('analista', 'Analista de Dados'), ('tecnico', 'Técnico de Campo'), ('agricultor', 'Agricultor')], default='visitante', max_length=20, verbose_name='Tipo de utilizador'),
        ),
    ]
