# Generated by Django 5.0 on 2026-07-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_utilizador_justificativa_solicitacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='cv_solicitacao',
            field=models.FileField(blank=True, null=True, upload_to='cv_solicitacoes/', verbose_name='CV em PDF'),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='validacao_profissional',
            field=models.TextField(blank=True, verbose_name='Validação profissional'),
        ),
    ]
