# Generated by Django 5.0 on 2026-07-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_utilizador_cv_solicitacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='perfil_solicitado',
            field=models.CharField(blank=True, choices=[('visitante', 'Visitante'), ('consultor', 'Consultor Agrícola'), ('analista', 'Analista de Dados'), ('tecnico', 'Técnico de Campo'), ('agricultor', 'Agricultor'), ('cliente', 'Cliente')], max_length=20, verbose_name='Perfil solicitado'),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='tipo_utilizador',
            field=models.CharField(choices=[('visitante', 'Visitante'), ('admin', 'Administrador'), ('consultor', 'Consultor Agrícola'), ('analista', 'Analista de Dados'), ('tecnico', 'Técnico de Campo'), ('agricultor', 'Agricultor'), ('cliente', 'Cliente')], default='visitante', max_length=20, verbose_name='Tipo de utilizador'),
        ),
    ]
