# Generated by Django 5.0 on 2026-07-17 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_utilizador_perfil_solicitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='data_solicitacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da solicitação'),
        ),
        migrations.CreateModel(
            name='MensagemSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('solicitacao', 'Solicitação de perfil'), ('acesso', 'Acesso ao sistema'), ('dados', 'Dados ou informação'), ('tecnico', 'Problema técnico'), ('outro', 'Outro assunto')], default='outro', max_length=20)),
                ('assunto', models.CharField(max_length=160)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em análise'), ('respondida', 'Respondida'), ('encerrada', 'Encerrada')], default='aberta', max_length=20)),
                ('resposta_admin', models.TextField(blank=True, verbose_name='Resposta da administração')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('respondida_em', models.DateTimeField(blank=True, null=True)),
                ('resposta_lida', models.BooleanField(default=False)),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_suporte', to=settings.AUTH_USER_MODEL)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_suporte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem de suporte',
                'verbose_name_plural': 'Mensagens de suporte',
                'ordering': ['-atualizada_em'],
            },
        ),
    ]
