# Generated by Django 5.0 on 2026-07-18 12:25

import contas.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_utilizador_data_solicitacao_mensagemsuporte'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilizador',
            managers=[
                ('objects', contas.models.UtilizadorManager()),
            ],
        ),
    ]
