# Generated by Django 5.0 on 2026-07-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Titulo')),
                ('palavras_chave', models.CharField(help_text='Separe por virgulas. Ex: clima, chuva, meteorologia', max_length=255, verbose_name='Palavras-chave')),
                ('resposta', models.TextField(verbose_name='Resposta')),
                ('perfil', models.CharField(choices=[('todos', 'Todos'), ('visitante', 'Visitante'), ('admin', 'Administrador'), ('consultor', 'Consultor Agricola'), ('analista', 'Analista de Dados'), ('tecnico', 'Tecnico de Campo'), ('agricultor', 'Agricultor')], default='todos', max_length=20, verbose_name='Perfil')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Resposta do Chatbot',
                'verbose_name_plural': 'Respostas do Chatbot',
                'ordering': ['perfil', 'titulo'],
            },
        ),
    ]
