# Generated by Django 5.0 on 2026-07-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostachatbot',
            name='perfil',
            field=models.CharField(choices=[('todos', 'Todos'), ('visitante', 'Visitante'), ('admin', 'Administrador'), ('consultor', 'Consultor Agricola'), ('analista', 'Analista de Dados'), ('tecnico', 'Tecnico de Campo'), ('agricultor', 'Agricultor'), ('cliente', 'Cliente')], default='todos', max_length=20, verbose_name='Perfil'),
        ),
    ]
