# Generated by Django 5.0 on 2026-07-10 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da cultura')),
                ('ciclo', models.CharField(help_text='Ex: Anual, Semestral', max_length=50, verbose_name='Ciclo')),
                ('epoca_plantio', models.CharField(blank=True, max_length=100, verbose_name='Época de plantio')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Cultura',
                'verbose_name_plural': 'Culturas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da propriedade')),
                ('localizacao', models.CharField(blank=True, max_length=200, verbose_name='Localização')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área total (hectares)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de registo')),
                ('consultor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propriedades_consultadas', to=settings.AUTH_USER_MODEL, verbose_name='Consultor responsável')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário (Agricultor)')),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do talhão')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área (hectares)')),
                ('tipo_solo', models.CharField(blank=True, max_length=100, verbose_name='Tipo de solo')),
                ('data_plantio', models.DateField(blank=True, null=True, verbose_name='Data de plantio')),
                ('cultura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='propriedades.cultura', verbose_name='Cultura')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='propriedades.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Talhão',
                'verbose_name_plural': 'Talhões',
                'ordering': ['propriedade', 'nome'],
            },
        ),
    ]
