# Generated by Django 5.0 on 2026-07-18 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultura',
            name='imagem_referencia',
            field=models.ImageField(blank=True, null=True, upload_to='culturas/', verbose_name='Imagem de referência'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='foto_capa',
            field=models.ImageField(blank=True, null=True, upload_to='propriedades/', verbose_name='Foto de capa'),
        ),
        migrations.AddField(
            model_name='talhao',
            name='estadio_fenologico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estádio fenológico'),
        ),
        migrations.AddField(
            model_name='talhao',
            name='foto_atual',
            field=models.ImageField(blank=True, null=True, upload_to='talhoes/', verbose_name='Foto atual do talhão'),
        ),
        migrations.CreateModel(
            name='RegistoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campanha', models.CharField(help_text='Ex.: 2025/2026', max_length=80, verbose_name='Campanha')),
                ('data_colheita', models.DateField(verbose_name='Data da colheita')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantidade')),
                ('unidade', models.CharField(choices=[('kg', 'Quilogramas'), ('t', 'Toneladas'), ('sc', 'Sacos')], default='kg', max_length=5, verbose_name='Unidade')),
                ('qualidade', models.CharField(blank=True, max_length=120, verbose_name='Qualidade/classificação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('foto_colheita', models.ImageField(blank=True, null=True, upload_to='colheitas/', verbose_name='Foto da produção/colheita')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registos_producao', to='propriedades.talhao', verbose_name='Talhão')),
            ],
            options={
                'verbose_name': 'Registo de produção',
                'verbose_name_plural': 'Registos de produção',
                'ordering': ['-data_colheita'],
            },
        ),
    ]
