# Generated by Django 5.0 on 2026-07-18 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0002_cultura_imagem_referencia_propriedade_foto_capa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='clientes_autorizados',
            field=models.ManyToManyField(blank=True, help_text='Compradores que podem consultar produção e relatórios emitidos desta propriedade.', limit_choices_to={'tipo_utilizador': 'cliente'}, related_name='fornecedores_autorizados', to=settings.AUTH_USER_MODEL, verbose_name='Clientes compradores autorizados'),
        ),
    ]
