# Generated by Django 5.0 on 2026-07-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0003_propriedade_clientes_autorizados'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='descricao_comercial',
            field=models.TextField(blank=True, help_text='Resumo público para compradores: culturas, capacidade, qualidade e condições de fornecimento.', verbose_name='Apresentação comercial'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='exposta_para_clientes',
            field=models.BooleanField(default=False, help_text='Quando ativo, clientes podem ver a apresentação comercial desta propriedade.', verbose_name='Expor no Mercado Agrícola'),
        ),
    ]
