# Generated by Django 5.0 on 2026-07-18 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0004_propriedade_descricao_comercial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='favoritada_por',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo_utilizador': 'cliente'}, related_name='propriedades_favoritas', to=settings.AUTH_USER_MODEL, verbose_name='Favoritada por clientes'),
        ),
        migrations.AddField(
            model_name='registoproducao',
            name='estado_comercial',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], default='disponivel', max_length=12, verbose_name='Estado comercial'),
        ),
    ]
