# Generated by Django 5.0 on 2026-07-21 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0005_propriedade_favoritada_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='analista_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_utilizador': 'analista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propriedades_analisadas', to=settings.AUTH_USER_MODEL, verbose_name='Analista de dados responsável'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='tecnico_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_utilizador': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propriedades_tecnicas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico de campo responsável'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome da propriedade'),
        ),
        migrations.AlterField(
            model_name='talhao',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do talhão'),
        ),
    ]
