# Generated by Django 5.0 on 2026-07-22 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0006_propriedade_analista_responsavel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_pretendida', models.CharField(blank=True, max_length=120)),
                ('contacto', models.CharField(max_length=160)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente na administração'), ('aguarda_agricultor', 'Aguardando confirmação do agricultor'), ('confirmado', 'Disponibilidade confirmada'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=24)),
                ('resposta_agricultor', models.BooleanField(blank=True, null=True)),
                ('observacao_agricultor', models.TextField(blank=True)),
                ('nota_administracao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo_utilizador': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_compra', to=settings.AUTH_USER_MODEL)),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_decididos', to=settings.AUTH_USER_MODEL)),
                ('producao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra', to='propriedades.registoproducao')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_compra', to='propriedades.propriedade')),
            ],
            options={
                'verbose_name': 'Pedido de compra',
                'verbose_name_plural': 'Pedidos de compra',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
