# Generated by Django 5.0 on 2026-07-10 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propriedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('geada', 'Risco de Geada'), ('seca', 'Risco de Seca'), ('praga', 'Alerta de Praga'), ('chuva_excessiva', 'Chuva Excessiva'), ('calor_extremo', 'Calor Extremo'), ('vento_forte', 'Vento Forte')], max_length=20, verbose_name='Tipo de alerta')),
                ('severidade', models.CharField(choices=[('info', 'Informativo'), ('aviso', 'Aviso'), ('urgente', 'Urgente')], default='aviso', max_length=10, verbose_name='Severidade')),
                ('mensagem', models.TextField(verbose_name='Mensagem do alerta')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data do alerta')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='propriedades.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RegistroClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura (°C)')),
                ('humidade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humidade (%)')),
                ('precipitacao', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precipitação (mm)')),
                ('vento_velocidade', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Vento (km/h)')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Condição')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registos_clima', to='propriedades.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Registo de Clima',
                'verbose_name_plural': 'Registos de Clima',
                'ordering': ['-data'],
            },
        ),
    ]
