# Generated by Django 5.0 on 2026-07-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(choices=[('openweather', 'OpenWeatherMap (requer chave)'), ('openmeteo', 'Open-Meteo (gratuito, sem chave)')], default='openweather', help_text='Escolha o provedor da API meteorológica.', max_length=20, verbose_name='Provedor meteorológico')),
                ('api_key', models.CharField(blank=True, help_text='Necessária para OpenWeatherMap. Deixe vazio se usar Open-Meteo.', max_length=200, verbose_name='Chave da API (API Key)')),
                ('url_base', models.CharField(blank=True, help_text='Opcional: URL customizada. Deixe vazio para usar a padrão.', max_length=200, verbose_name='URL base da API')),
                ('cidade_padrao', models.CharField(default='Luanda', help_text='Cidade usada por defeito ao testar a API.', max_length=100, verbose_name='Cidade padrão (para testes)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Configuração ativa')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração da API',
                'verbose_name_plural': 'Configuração da API',
            },
        ),
    ]
