# Generated by Django 5.0 on 2026-07-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoapi',
            name='ia_api_key',
            field=models.CharField(blank=True, help_text='Cole aqui a chave criada no Google AI Studio.', max_length=255, verbose_name='Chave da API Google/Gemini'),
        ),
        migrations.AddField(
            model_name='configuracaoapi',
            name='ia_ativo',
            field=models.BooleanField(default=False, help_text='Quando desligado, o sistema usa apenas regras internas e respostas programadas.', verbose_name='IA externa ativa'),
        ),
        migrations.AddField(
            model_name='configuracaoapi',
            name='ia_modelo',
            field=models.CharField(default='gemini-1.5-flash', help_text='Exemplo: gemini-1.5-flash. Pode trocar conforme o modelo disponível na sua chave.', max_length=80, verbose_name='Modelo de IA'),
        ),
        migrations.AddField(
            model_name='configuracaoapi',
            name='ia_provedor',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('nenhum', 'Sem API externa')], default='gemini', help_text='Provedor usado pelo assistente e pelas sugestões automáticas.', max_length=20, verbose_name='Provedor de IA'),
        ),
        migrations.AddField(
            model_name='configuracaoapi',
            name='ia_url_base',
            field=models.CharField(blank=True, help_text='Opcional. Deixe vazio para usar a URL padrão do Gemini.', max_length=255, verbose_name='URL base da API de IA'),
        ),
    ]
