# Generated by Django 5.0 on 2026-07-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_sistema', '0002_configuracaoapi_ia_api_key_configuracaoapi_ia_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoapi',
            name='cadastro_senha_exigir_letra',
            field=models.BooleanField(default=True, verbose_name='Exigir pelo menos uma letra na nova senha'),
        ),
        migrations.AddField(
            model_name='configuracaoapi',
            name='cadastro_senha_exigir_numero',
            field=models.BooleanField(default=True, verbose_name='Exigir pelo menos um número na nova senha'),
        ),
        migrations.AddField(
            model_name='configuracaoapi',
            name='login_exigir_identificador_valido',
            field=models.BooleanField(default=True, verbose_name='Bloquear login com identificador apenas de símbolos'),
        ),
        migrations.AddField(
            model_name='configuracaoapi',
            name='login_exigir_senha_alfanumerica',
            field=models.BooleanField(default=True, verbose_name='Bloquear login com senha apenas de símbolos'),
        ),
        migrations.AddField(
            model_name='configuracaoapi',
            name='permitir_login_por_nome',
            field=models.BooleanField(default=True, help_text='Se desligado, o login será permitido somente por email.', verbose_name='Permitir login por nome completo'),
        ),
        migrations.AddField(
            model_name='configuracaoapi',
            name='validar_nome_seguro',
            field=models.BooleanField(default=True, verbose_name='Bloquear nomes formados apenas por símbolos'),
        ),
    ]
